In [7]:
#%pip install tensorflow

from tensorflow.keras.preprocessing.text import one_hot


In [8]:
### sentences 

sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
     ]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
##Define the vocabulary size
vocab_size = 10000

In [29]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [30]:
# One hot Representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[169, 6620, 547, 9658],
 [169, 6620, 547, 1262],
 [169, 6633, 547, 3381],
 [2754, 5211, 6888, 8489, 1504],
 [2754, 5211, 6888, 8489, 9969],
 [1930, 169, 3223, 547, 3864],
 [477, 6271, 3266, 8489]]

In [31]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [33]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  169 6620  547 9658]
 [   0    0    0    0  169 6620  547 1262]
 [   0    0    0    0  169 6633  547 3381]
 [   0    0    0 2754 5211 6888 8489 1504]
 [   0    0    0 2754 5211 6888 8489 9969]
 [   0    0    0 1930  169 3223  547 3864]
 [   0    0    0    0  477 6271 3266 8489]]


In [34]:
#feature representation (categorize data is dim)
dim = 10

In [39]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [40]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


array([[[ 1.46191195e-03,  3.98594476e-02,  3.02911513e-02,
         -4.00526524e-02,  2.85364725e-02,  2.41250880e-02,
         -1.81773081e-02,  2.81198286e-02,  2.20591314e-02,
          1.04448944e-03],
        [ 1.46191195e-03,  3.98594476e-02,  3.02911513e-02,
         -4.00526524e-02,  2.85364725e-02,  2.41250880e-02,
         -1.81773081e-02,  2.81198286e-02,  2.20591314e-02,
          1.04448944e-03],
        [ 1.46191195e-03,  3.98594476e-02,  3.02911513e-02,
         -4.00526524e-02,  2.85364725e-02,  2.41250880e-02,
         -1.81773081e-02,  2.81198286e-02,  2.20591314e-02,
          1.04448944e-03],
        [ 1.46191195e-03,  3.98594476e-02,  3.02911513e-02,
         -4.00526524e-02,  2.85364725e-02,  2.41250880e-02,
         -1.81773081e-02,  2.81198286e-02,  2.20591314e-02,
          1.04448944e-03],
        [ 2.03572251e-02, -7.63036311e-04, -2.33674180e-02,
         -3.75605002e-02,  3.06997187e-02, -2.45028622e-02,
          7.00203329e-03, -1.79863349e-02,  4.440474